version: '3.8'

services:
  mariadb:
    image: mariadb:11.5.1-ubi9-rc
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin-pw
      MYSQL_DATABASE: tododot
      MYSQL_USER: todo-admin
      MYSQL_PASSWORD: admin-pw
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
